### ISSUE TITLE
Maintainer application

### ISSUE THREAD

**Issue by gramedek** [JDALab/otaku-watcher#6]
I'm not really that good, so I don't know if I'm going to write new scrapers, but I can at least try and maintain the plugin in a working state.
If you check my MR/PR, you'll see I fixed an issue where the scraper can find streamwish, but the page isn't formatted as expected so it crashes when it tries to parse it.
The behaviour I wrote tries to get the url for streamwish, and if it fails, tries from doodstream, allowing for any amount of different sources to be checked until one works.

(if you wanna see some of my python background, check owega on pypi, all of my stuff is usually hosted on my own gitlab instance so I don't really have a history here)

_Originally posted by @gramedek in https://github.com/JDALab/otaku-watcher/issues/2#issuecomment-2255760355_

**Comment by lowpolyv2** [comment]
Really sorry for not seeing that comment earlier but yeah your experience / python background checks out. 🌟 I'm down to make you maintainer of the otaku-watcher plugin soon but for now I'll let you continue with prs then I'll think of promoting you to an actual maintainer in the repo or organization.

You don't have to write new scrapers but if you want and you need help, just open an issue and I can help you in my free time. 😊

**Comment by lowpolyv2** [comment]
I actually just created a discord account a few days ago to join the mov-cli guild, it should be `lowpolyv2`. I'll accept the friend invite when I'm on my computer. 😊
